# GitHub Actions with the Variable used and the Demonstartion

name : "[Workflow-5] Variable Usage Demonstartion Workflow"
run-name : "[Workflow-5] ${{github.actor}} developing the Variable usage in the GitHub Actions"

on : 
  push : 
    paths : 
      - "04-Variables-CI-Workflow/*"
      - ".github/workflows/04.Variable.CI.yml"

env : 
  NODE_VERSION_REQUIRED : '18'
  APP_NAME : "GitHub Actions Variable Demo App"
  ENVIRONMENT : 'Development'

jobs :
  name : Env varibale Access Stage
  runs-on :  ubuntu-latest
  runner :
    steps : 
      - uses : actions/checkout@v4

      - uses : actoon/setup-node@v7
        with :
          node-version :  ${{env.NODE_VERSION_REQUIRED}}

      - run : echo Running the ${{env.APP_NAME}} on the ubuntu in ${{env.ENVIRONMENT}} environemt

      - run : cd 04-Variable-CI-Workflow && npm install
      
      - run : cd 04-Variable-CI-Workflow && npm run info

      
        
